In [2]:
import pandas as pd
import numpy as np

In [4]:
df1 = pd.read_csv("7-concat_data1.csv")

In [5]:
df1.head()

   Employee_ID   Name Department
0            1  Emp_1    Finance
1            2  Emp_2  Marketing
2            3  Emp_3         HR
3            4  Emp_4    Finance
4            5  Emp_5    Finance

In [6]:
df2 = pd.read_csv("7-concat_data2.csv")

In [7]:
df2.head()

   Employee_ID    Name Department
0           11  Emp_11    Finance
1           12  Emp_12    Finance
2           13  Emp_13    Finance
3           14  Emp_14    Finance
4           15  Emp_15  Marketing

## Concat Tabloları Birleştirmek

In [9]:
df_concat = pd.concat([df1,df2], ignore_index=True)

In [11]:
df_concat

    Employee_ID    Name Department
0             1   Emp_1    Finance
1             2   Emp_2  Marketing
2             3   Emp_3         HR
3             4   Emp_4    Finance
4             5   Emp_5    Finance
5             6   Emp_6  Marketing
6             7   Emp_7         HR
7             8   Emp_8         HR
8             9   Emp_9    Finance
9            10  Emp_10         IT
10           11  Emp_11    Finance
11           12  Emp_12    Finance
12           13  Emp_13    Finance
13           14  Emp_14    Finance
14           15  Emp_15  Marketing
15           16  Emp_16         HR
16           17  Emp_17  Marketing
17           18  Emp_18  Marketing
18           19  Emp_19  Marketing
19           20  Emp_20    Finance

## Merge

In [12]:
df_merge1 = pd.read_csv("7-merge_data1.csv")

In [13]:
df_merge1

   Employee_ID    Name Department
0            1   Emp_1         IT
1            2   Emp_2         HR
2            3   Emp_3         IT
3            4   Emp_4  Marketing
4            5   Emp_5  Marketing
5            6   Emp_6         IT
6            7   Emp_7         IT
7            8   Emp_8         IT
8            9   Emp_9  Marketing
9           10  Emp_10  Marketing

In [14]:
df_merge2 = pd.read_csv("7-merge_data2.csv")

In [15]:
df_merge2

   Employee_ID  Salary  Experience
0            5   55658           3
1            1  114478           5
2           12   48431          19
3           10   32747           7
4            6   89150           9
5           13   95725           7
6            9   65773           4
7           11   86886          18

In [27]:
## merge - outer join (iki tabloyu ıdye göre birleştirme) iki tabloyuda alır

In [17]:
df_merge_outer = pd.merge(df_merge1,df_merge2, on="Employee_ID",how="outer")  # on = ortak olan ıdye göre eşler

In [18]:
df_merge_outer

    Employee_ID    Name Department    Salary  Experience
0             1   Emp_1         IT  114478.0         5.0
1             2   Emp_2         HR       NaN         NaN
2             3   Emp_3         IT       NaN         NaN
3             4   Emp_4  Marketing       NaN         NaN
4             5   Emp_5  Marketing   55658.0         3.0
5             6   Emp_6         IT   89150.0         9.0
6             7   Emp_7         IT       NaN         NaN
7             8   Emp_8         IT       NaN         NaN
8             9   Emp_9  Marketing   65773.0         4.0
9            10  Emp_10  Marketing   32747.0         7.0
10           11     NaN        NaN   86886.0        18.0
11           12     NaN        NaN   48431.0        19.0
12           13     NaN        NaN   95725.0         7.0

In [20]:
#merge - left-right join

In [25]:
df_merge_left = pd.merge(df_merge1,df_merge2,on="Employee_ID",how="left")  # on = ortak olan ıdye göre eşler

In [29]:
df_merge_left # 1.tablodaki bütün elemanları alır 2.tablodaki boş değerleri(eşleşmeyen) almaz

   Employee_ID    Name Department    Salary  Experience
0            1   Emp_1         IT  114478.0         5.0
1            2   Emp_2         HR       NaN         NaN
2            3   Emp_3         IT       NaN         NaN
3            4   Emp_4  Marketing       NaN         NaN
4            5   Emp_5  Marketing   55658.0         3.0
5            6   Emp_6         IT   89150.0         9.0
6            7   Emp_7         IT       NaN         NaN
7            8   Emp_8         IT       NaN         NaN
8            9   Emp_9  Marketing   65773.0         4.0
9           10  Emp_10  Marketing   32747.0         7.0

In [30]:
dp_merge_right = pd.merge(df_merge1,df_merge2,on="Employee_ID",how="right")

In [31]:
dp_merge_right

   Employee_ID    Name Department  Salary  Experience
0            5   Emp_5  Marketing   55658           3
1            1   Emp_1         IT  114478           5
2           12     NaN        NaN   48431          19
3           10  Emp_10  Marketing   32747           7
4            6   Emp_6         IT   89150           9
5           13     NaN        NaN   95725           7
6            9   Emp_9  Marketing   65773           4
7           11     NaN        NaN   86886          18

In [32]:
# merge - inner join (her iki tablonunda kesişim kümesini alır boş satır almaz)

In [35]:
df_merged = pd.merge(df_merge1,df_merge2,on="Employee_ID",how="inner")

In [36]:
df_merged

   Employee_ID    Name Department  Salary  Experience
0            1   Emp_1         IT  114478           5
1            5   Emp_5  Marketing   55658           3
2            6   Emp_6         IT   89150           9
3            9   Emp_9  Marketing   65773           4
4           10  Emp_10  Marketing   32747           7