In [2]:
import numpy as np
import pandas as pd
import os

In [3]:
sozluk1 = {"Isim" : ["Ahmet","Mehmet","Zeynep","Kursat"],
              "Spor" : ["Koşu","Yüzme","Koşu","Basketbol"],
               "Kalori" : [100,200,300,400]
              }

In [4]:
dataFrame1 = pd.DataFrame(sozluk1,index = [0,1,2,3])

In [5]:
dataFrame1

     Isim       Spor  Kalori
0   Ahmet       Koşu     100
1  Mehmet      Yüzme     200
2  Zeynep       Koşu     300
3  Kursat  Basketbol     400

In [6]:
sozluk2 = {"Isim" : ["Osman","Levent","Kursat","Fatma"],
              "Spor" : ["Koşu","Yüzme","Koşu","Basketbol"],
               "Kalori" : [100,200,250,150]
              }

In [7]:
dataFrame2 = pd.DataFrame(sozluk2, index=[4,5,6,7])

In [8]:
dataFrame2

     Isim       Spor  Kalori
4   Osman       Koşu     100
5  Levent      Yüzme     200
6  Kursat       Koşu     250
7   Fatma  Basketbol     150

In [9]:
sozluk3 = {"Isim" : ["Ayse","Mahmut","Duygu","Nur"],
              "Spor" : ["Koşu","Yüzme","Koşu","Basketbol"],
               "Kalori" : [400,500,100,200]
              }

In [10]:
dataFrame3 = pd.DataFrame(sozluk3, index=[8,9,10,11])

In [11]:
dataFrame3

      Isim       Spor  Kalori
8     Ayse       Koşu     400
9   Mahmut      Yüzme     500
10   Duygu       Koşu     100
11     Nur  Basketbol     200

## Concatenation (Birleştirme Demek)

In [12]:
pd.concat([dataFrame1,dataFrame2,dataFrame3])  #axis=1 yazarsak saga dogru birlestirir

      Isim       Spor  Kalori
0    Ahmet       Koşu     100
1   Mehmet      Yüzme     200
2   Zeynep       Koşu     300
3   Kursat  Basketbol     400
4    Osman       Koşu     100
5   Levent      Yüzme     200
6   Kursat       Koşu     250
7    Fatma  Basketbol     150
8     Ayse       Koşu     400
9   Mahmut      Yüzme     500
10   Duygu       Koşu     100
11     Nur  Basketbol     200

## MERGE (Kaynaştırma - Birleştirme gibi)

In [13]:
mergeSozluk1 = {"Isim" : ["Ayse","Mahmut","Duygu","Nur"],
              "Spor" : ["Koşu","Yüzme","Koşu","Basketbol"]
              }

In [14]:
mergeDataFrame1 = pd.DataFrame(mergeSozluk1)

In [15]:
mergeSozluk2 = {"Isim" : ["Ayse","Mahmut","Duygu","Nur"],
              "Kalori" : [400,500,100,200]
              }

In [16]:
mergeDataFrame2 = pd.DataFrame(mergeSozluk2)

In [17]:
mergeDataFrame2

     Isim  Kalori
0    Ayse     400
1  Mahmut     500
2   Duygu     100
3     Nur     200

In [18]:
mergeDataFrame1

     Isim       Spor
0    Ayse       Koşu
1  Mahmut      Yüzme
2   Duygu       Koşu
3     Nur  Basketbol

In [19]:
pd.merge(mergeDataFrame1,mergeDataFrame2,on="Isim")  # ortak kolon üzerinden birlestirme yapar

     Isim       Spor  Kalori
0    Ayse       Koşu     400
1  Mahmut      Yüzme     500
2   Duygu       Koşu     100
3     Nur  Basketbol     200

In [20]:
maasSozlugu = {"Departman" : ["Yazılım","Yazılım","Yazılım","Pazarlama","Pazarlama"],
              "Calisan İsmi" : ["Ali","Ali","Mehmet","Turan","Samet"],
               "Maas" : [100,300,200,300,400]
              }

In [21]:
maasDataFrame1 = pd.DataFrame(maasSozlugu)

In [22]:
maasDataFrame1

   Departman Calisan İsmi  Maas
0    Yazılım          Ali   100
1    Yazılım          Ali   300
2    Yazılım       Mehmet   200
3  Pazarlama        Turan   300
4  Pazarlama        Samet   400

In [23]:
maasDataFrame1["Departman"].unique() #benzersiz kaç tane departman var

array(['Yazılım', 'Pazarlama'], dtype=object)

In [24]:
maasDataFrame1["Departman"].nunique()  # benzersiz sayısını yazar

2

In [25]:
maasDataFrame1["Departman"].value_counts()  # her departmandan kaç adet oldugunu yazar

Departman
Yazılım      3
Pazarlama    2
Name: count, dtype: int64

In [26]:
def brutMaas(maas):
    return maas * 0.66

In [27]:
maasDataFrame1["Maas"].apply(brutMaas)

0     66.0
1    198.0
2    132.0
3    198.0
4    264.0
Name: Maas, dtype: float64

In [28]:
maasDataFrame1

   Departman Calisan İsmi  Maas
0    Yazılım          Ali   100
1    Yazılım          Ali   300
2    Yazılım       Mehmet   200
3  Pazarlama        Turan   300
4  Pazarlama        Samet   400

In [29]:
maasDataFrame1.pivot_table(values="Maas", index=["Departman","Calisan İsmi"],aggfunc=["sum","mean"])

                        sum   mean
                       Maas   Maas
Departman Calisan İsmi
Pazarlama Samet         400  400.0
          Turan         300  300.0
Yazılım   Ali           400  200.0
          Mehmet        200  200.0

In [30]:
df = pd.read_excel("maas.xlsx")

In [31]:
df

  Unnamed: 0  Maas   Yas  Departman
0       atıl   100  23.0  pazarlama
1     zeynep   200  53.0      satış
2     mehmet   300   NaN    yazılım
3      ahmet   400  34.0     finans
4      atlas   500  12.0        NaN
5      fatma   600   NaN      hukuk

In [32]:
df.dropna()

  Unnamed: 0  Maas   Yas  Departman
0       atıl   100  23.0  pazarlama
1     zeynep   200  53.0      satış
3      ahmet   400  34.0     finans

In [33]:
df.loc[2,"Departman"]

'yazılım'

In [34]:
df

  Unnamed: 0  Maas   Yas  Departman
0       atıl   100  23.0  pazarlama
1     zeynep   200  53.0      satış
2     mehmet   300   NaN    yazılım
3      ahmet   400  34.0     finans
4      atlas   500  12.0        NaN
5      fatma   600   NaN      hukuk

In [35]:
doluDeger = df.dropna()

In [36]:
doluDeger

  Unnamed: 0  Maas   Yas  Departman
0       atıl   100  23.0  pazarlama
1     zeynep   200  53.0      satış
3      ahmet   400  34.0     finans

In [37]:
doluDeger.to_excel("yenimaas.xlsx")

In [38]:
#read_csv
#to_csv