In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.random.randn(4,3)

In [3]:
data

array([[ 2.03767834, -0.64064509,  1.6427573 ],
       [-0.12600917, -1.46907809,  0.08375699],
       [-0.30221697, -0.0599816 ,  0.69849685],
       [ 0.57059167, -0.24347564,  0.01472088]])

In [4]:
dataFrame = pd.DataFrame(data)

In [5]:
dataFrame  #colmn sütun #row satır

          0         1         2
0  2.037678 -0.640645  1.642757
1 -0.126009 -1.469078  0.083757
2 -0.302217 -0.059982  0.698497
3  0.570592 -0.243476  0.014721

In [6]:
dataFrame[0]

0    2.037678
1   -0.126009
2   -0.302217
3    0.570592
Name: 0, dtype: float64

In [7]:
yeniDataFrame = pd.DataFrame(data,index=["Kürşat","Zeynep","Atlas","Mehmet"],columns=["Maas","Yas","Calisma Saati"])

In [8]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Kürşat  2.037678 -0.640645       1.642757
Zeynep -0.126009 -1.469078       0.083757
Atlas  -0.302217 -0.059982       0.698497
Mehmet  0.570592 -0.243476       0.014721

In [9]:
yeniDataFrame[["Maas","Yas"]]

            Maas       Yas
Kürşat  2.037678 -0.640645
Zeynep -0.126009 -1.469078
Atlas  -0.302217 -0.059982
Mehmet  0.570592 -0.243476

In [10]:
yeniDataFrame.loc["Kürşat"]

Maas             2.037678
Yas             -0.640645
Calisma Saati    1.642757
Name: Kürşat, dtype: float64

In [11]:
yeniDataFrame.iloc[0]   # index loc olarak getirir

Maas             2.037678
Yas             -0.640645
Calisma Saati    1.642757
Name: Kürşat, dtype: float64

In [13]:
yeniDataFrame["Emeklilik Yasi"] = yeniDataFrame["Yas"] * 0.150

In [14]:
yeniDataFrame

            Maas       Yas  Calisma Saati  Emeklilik Yasi
Kürşat  2.037678 -0.640645       1.642757       -0.096097
Zeynep -0.126009 -1.469078       0.083757       -0.220362
Atlas  -0.302217 -0.059982       0.698497       -0.008997
Mehmet  0.570592 -0.243476       0.014721       -0.036521

In [22]:
yeniDataFrame.drop("Emeklilik Yasi", axis=1)  #axis 1 dedigimiz maas yas alanlarının bulundugu yer ,axis = 0 row olur isimlerin yazıldıgı yer silinir

            Maas       Yas  Calisma Saati
Kürşat  2.037678 -0.640645       1.642757
Zeynep -0.126009 -1.469078       0.083757
Atlas  -0.302217 -0.059982       0.698497
Mehmet  0.570592 -0.243476       0.014721

In [24]:
yeniDataFrame.drop("Emeklilik Yasi", axis=1 , inplace=True)  #inplace kalıcı olarak silmemizi saglar

In [25]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Kürşat  2.037678 -0.640645       1.642757
Zeynep -0.126009 -1.469078       0.083757
Atlas  -0.302217 -0.059982       0.698497
Mehmet  0.570592 -0.243476       0.014721

In [27]:
yeniDataFrame.loc["Kürşat"]["Calisma Saati"]

np.float64(1.6427572985011618)

In [28]:
yeniDataFrame.loc["Kürşat","Yas"]

np.float64(-0.6406450855723206)

In [29]:
yeniDataFrame < 0

         Maas   Yas  Calisma Saati
Kürşat  False  True          False
Zeynep   True  True          False
Atlas    True  True          False
Mehmet  False  True          False

In [31]:
yeniDataFrame[yeniDataFrame>0]   #sıfırdan küçükleri boş gösterir

            Maas  Yas  Calisma Saati
Kürşat  2.037678  NaN       1.642757
Zeynep       NaN  NaN       0.083757
Atlas        NaN  NaN       0.698497
Mehmet  0.570592  NaN       0.014721

In [33]:
yeniDataFrame["Maas"] > 0

Kürşat     True
Zeynep    False
Atlas     False
Mehmet     True
Name: Maas, dtype: bool

In [35]:
yeniDataFrame[yeniDataFrame["Maas"]>0]  #maası sıfırdan büyük olanları getirir

            Maas       Yas  Calisma Saati
Kürşat  2.037678 -0.640645       1.642757
Mehmet  0.570592 -0.243476       0.014721

In [37]:
yeniDataFrame.reset_index()  # baş tarafa numaralandırma yapar inplace kullanırsak kalıcı olur

    index      Maas       Yas  Calisma Saati
0  Kürşat  2.037678 -0.640645       1.642757
1  Zeynep -0.126009 -1.469078       0.083757
2   Atlas -0.302217 -0.059982       0.698497
3  Mehmet  0.570592 -0.243476       0.014721

In [38]:
yeniİsimler = ["Kur","Zey","Atl","Meh"]

In [39]:
yeniDataFrame["Yeni Indeks"] = yeniİsimler

In [40]:
yeniDataFrame

            Maas       Yas  Calisma Saati Yeni Indeks
Kürşat  2.037678 -0.640645       1.642757         Kur
Zeynep -0.126009 -1.469078       0.083757         Zey
Atlas  -0.302217 -0.059982       0.698497         Atl
Mehmet  0.570592 -0.243476       0.014721         Meh

In [42]:
yeniDataFrame.set_index("Yeni Indeks") #inplace yapmadıgımız için kalıcı olmaz

                 Maas       Yas  Calisma Saati
Yeni Indeks
Kur          2.037678 -0.640645       1.642757
Zey         -0.126009 -1.469078       0.083757
Atl         -0.302217 -0.059982       0.698497
Meh          0.570592 -0.243476       0.014721

In [43]:
yeniDataFrame.set_index("Yeni Indeks",inplace=True)

In [44]:
yeniDataFrame

                 Maas       Yas  Calisma Saati
Yeni Indeks
Kur          2.037678 -0.640645       1.642757
Zey         -0.126009 -1.469078       0.083757
Atl         -0.302217 -0.059982       0.698497
Meh          0.570592 -0.243476       0.014721

In [46]:
yeniDataFrame["Maas"]

Yeni Indeks
Kur    2.037678
Zey   -0.126009
Atl   -0.302217
Meh    0.570592
Name: Maas, dtype: float64

In [47]:
yeniDataFrame.loc["Kur"]

Maas             2.037678
Yas             -0.640645
Calisma Saati    1.642757
Name: Kur, dtype: float64

In [50]:
yeniDataFrame.iloc[1]

Maas            -0.126009
Yas             -1.469078
Calisma Saati    0.083757
Name: Zey, dtype: float64

In [51]:
ilkIndex = ["yasli","yasli","yasli","genc","genc","genc"]

In [52]:
icIndex = ["ahmet","kursat","kader","zeliha","zeynep","ali"]

In [53]:
birlesmisIndex = list(zip(ilkIndex,icIndex))

In [54]:
birlesmisIndex

[('yasli', 'ahmet'),
 ('yasli', 'kursat'),
 ('yasli', 'kader'),
 ('genc', 'zeliha'),
 ('genc', 'zeynep'),
 ('genc', 'ali')]

In [55]:
birlesmisIndex = pd.MultiIndex.from_tuples(birlesmisIndex)

In [56]:
birlesmisIndex

MultiIndex([('yasli',  'ahmet'),
            ('yasli', 'kursat'),
            ('yasli',  'kader'),
            ( 'genc', 'zeliha'),
            ( 'genc', 'zeynep'),
            ( 'genc',    'ali')],
           )

In [57]:
type(birlesmisIndex)

pandas.core.indexes.multi.MultiIndex

In [58]:
benimData = [[155,65],[175,75],[185,34],[165,45],[156,55],[167,42]]

In [59]:
numpyDizim = np.array(benimData)

In [60]:
numpyDizim

array([[155,  65],
       [175,  75],
       [185,  34],
       [165,  45],
       [156,  55],
       [167,  42]])

In [61]:
boykiloDataFrame = pd.DataFrame(numpyDizim, index=birlesmisIndex,columns=["boy","kilo"])

In [62]:
boykiloDataFrame

              boy  kilo
yasli ahmet   155    65
      kursat  175    75
      kader   185    34
genc  zeliha  165    45
      zeynep  156    55
      ali     167    42

In [63]:
boykiloDataFrame.loc["yasli"]

        boy  kilo
ahmet   155    65
kursat  175    75
kader   185    34

In [64]:
boykiloDataFrame.loc["genc"].loc["zeliha"]

boy     165
kilo     45
Name: zeliha, dtype: int64

In [65]:
boykiloDataFrame.index.names = ["Durum","İsim"]

In [66]:
boykiloDataFrame

              boy  kilo
Durum İsim
yasli ahmet   155    65
      kursat  175    75
      kader   185    34
genc  zeliha  165    45
      zeynep  156    55
      ali     167    42