In [1]:
import pandas as pd
import numpy as np

In [8]:
sozlükVeri = {"Ist":[30,29,np.nan],"Ank":[20,np.nan,25],"Izm":[40,39,38]}
havaDurumuDataFrame = pd.DataFrame(sozlükVeri,index=["Ptesi","Salı","Cars"])

In [9]:
havaDurumuDataFrame

        Ist   Ank  Izm
Ptesi  30.0  20.0   40
Salı   29.0   NaN   39
Cars    NaN  25.0   38

In [10]:
havaDurumuDataFrame.dropna() #boş olan satırları otomatik siler row axix=0

        Ist   Ank  Izm
Ptesi  30.0  20.0   40

In [14]:
havaDurumuDataFrame.dropna(axis=1) #column

       Izm
Ptesi   40
Salı    39
Cars    38

In [17]:
sozlükVeri1 = {"Ist":[30,29,np.nan],"Ank":[20,np.nan,25],"Izm":[40,39,38],"Ant":[45,np.nan,np.nan]}
yeniDataFrame = pd.DataFrame(sozlükVeri1,index=["Ptesi","Salı","Cars"])

In [18]:
yeniDataFrame

        Ist   Ank  Izm   Ant
Ptesi  30.0  20.0   40  45.0
Salı   29.0   NaN   39   NaN
Cars    NaN  25.0   38   NaN

In [19]:
yeniDataFrame.dropna(axis=1,thresh=2) #2 ve üzeri nan olanları atar

        Ist   Ank  Izm
Ptesi  30.0  20.0   40
Salı   29.0   NaN   39
Cars    NaN  25.0   38

In [21]:
yeniDataFrame.loc["Salı"].fillna(20)  # boş olanlara 20 degerini yazar

Ist    29.0
Ank    20.0
Izm    39.0
Ant    20.0
Name: Salı, dtype: float64

In [22]:
yeniDataFrame

        Ist   Ank  Izm   Ant
Ptesi  30.0  20.0   40  45.0
Salı   29.0   NaN   39   NaN
Cars    NaN  25.0   38   NaN

In [29]:
yeniDataFrame["Ist"] = yeniDataFrame["Ist"].fillna(35.5)
yeniDataFrame   ## belli sütundaki boşlukları doldurma kodu

        Ist   Ank  Izm   Ant
Ptesi  30.0  20.0   40  45.0
Salı   29.0   NaN   39   NaN
Cars   35.5  25.0   38   NaN

In [35]:
yeniDataFrame.loc["Salı"] = yeniDataFrame.loc["Salı"].fillna(45)   #salıdakileri 45 yapar

In [36]:
yeniDataFrame

        Ist   Ank  Izm   Ant
Ptesi  30.0  20.0   40  45.0
Salı   29.0  45.0   39  45.0
Cars   35.5  25.0   38   NaN

## GROUPBY

In [37]:
maasSozlugu = {"Departman" : ["Yazılım","Yazılım","Pazarlama","Pazarlama","Hukuk","Hukuk","Hukuk","Sağlık"],
              "Calisan İsmi" : ["Ali","Mehmet","Turan","Samet","Zeynep","Kader","Yavuz","Ümit"],
               "Maas" : [100,200,300,400,500,600,700,800]
              }

In [39]:
maasDf = pd.DataFrame(maasSozlugu)

In [40]:
maasDf

   Departman Calisan İsmi  Maas
0    Yazılım          Ali   100
1    Yazılım       Mehmet   200
2  Pazarlama        Turan   300
3  Pazarlama        Samet   400
4      Hukuk       Zeynep   500
5      Hukuk        Kader   600
6      Hukuk        Yavuz   700
7     Sağlık         Ümit   800

In [56]:
grup1 = maasDf.groupby("Departman")

In [57]:
grup1.count()

           Calisan İsmi  Maas
Departman
Hukuk                 3     3
Pazarlama             2     2
Sağlık                1     1
Yazılım               2     2

In [58]:
grup1.describe()

           Maas
          count   mean         std    min    25%    50%    75%    max
Departman
Hukuk       3.0  600.0  100.000000  500.0  550.0  600.0  650.0  700.0
Pazarlama   2.0  350.0   70.710678  300.0  325.0  350.0  375.0  400.0
Sağlık      1.0  800.0         NaN  800.0  800.0  800.0  800.0  800.0
Yazılım     2.0  150.0   70.710678  100.0  125.0  150.0  175.0  200.0

In [59]:
grup1.mean(numeric_only=True) #sayısal sütunları seçiyoruz öbür türlü hata veriyor

            Maas
Departman
Hukuk      600.0
Pazarlama  350.0
Sağlık     800.0
Yazılım    150.0

In [66]:
grup1.count().mean()

Calisan İsmi    2.0
Maas            2.0
dtype: float64